version: '3'

services:
  google-oauth2:
    build: .
    container_name: google-oauth2-BabyUIAGI
    # depends_on:
    #   db:
    #     condition: service_healthy
    ports:
      - 3000:3000

  # MySQL
#   db:
#     image: mysql:8.0
#     container_name: mysql_auth
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       TZ: 'Asia/Tokyo'
#     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - mysql-data:/var/lib/mysql
#     ports:
#       - 3316:3306
#     healthcheck:
#       test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

# volumes:
#   mysql-data:
